### ISSUE TITLE
关于国际服hoyolab的cookie

### ISSUE THREAD

**Issue by Terebi1996** [Le-niao/Yunzai-Bot#190]
虽然获取了cookie，但是bot貌似不支持国际服。
请问有好的解决方案吗

**Comment by NomadThanatos** [comment]
Duplicate as #170 
I know there is a modified version that at least support oversea servers, but based on the history of that author, I do not believe he would have any respect for the free software.

So I just worked on this since today morning, and it now can support some operations for oversea servers.
Mostly stuff you need can be found here: https://github.com/Xm798/Genshin-Dailynote-Helper

My main concern is that I want to support both CN and oversea server together, and it seems this cannot be determined by cookies.

For CN you can get UID from https://api-takumi.mihoyo.com/binding/api/getUserGameRolesByCookie?game_biz=hk4e_cn
For oversea you can get UID from https://api-os-takumi.mihoyo.com/binding/api/getUserGameRolesByCookie?game_biz=hk4e_global

But before having UID, seems you cannot figure out the user's server based on cookies.

Hopefully I can have a easy and clean solution before weekend so I can publish a pull request.
Otherwise if you think you need the currently what I have, I can also put those changes out first.

**Comment by Terebi1996** [comment]
I noticed the global Hoyolab cookie always has an language info in it
mi18nLang = xxxx, 
which the CN Hoyolab doesn't. 
Could it possible use this to separate the CN and global server ?

**Comment by NomadThanatos** [comment]
Yeah I think even it is not a perfect solution but at least it is a clean workaround, I am working on the implementation now, it support the basic usage of this app.

Something that I am still working on:
1. Test CN server account.
2. Fix some URL to support fully usage.

**Comment by NomadThanatos** [comment]
Tried with a CN server account, found out the cookies also contain  `mi18nLang=zh-cn;` 😞

**Comment by NomadThanatos** [comment]
Actually it has 2 processes,
1. Send the full cookies(with `account_id` and `cookie_token`), it will get the UID from https://api-takumi.mihoyo.com/binding/api/getUserGameRolesByCookie?game_biz=hk4e_cn automatically, and it can provide full operations for the user.
2. Send the limited cookies(without `account_id` and `cookie_token`), it will ask the user to provide the UID in the next message, and it could only provide limited operations for this user, see [this](https://github.com/Le-niao/Yunzai-Bot/blob/master/lib/app/dailyNote.js#L382-L396), basically a user should not use this process.

And referring https://thesadru.github.io/genshin.py/configuration/ the Default Region section, you can see there is no way to determine the region by this package.

For now, I would say supporting oversea server would be a feature that breaks the previous user process.

Some solutions that neither of them I like.

1. Retry on failed, something like this.
    ```
    if (!bingCookie(e)) {
      bingCookie(e, oversea = true)
    }
    ```
1. Fork this with a version only support oversea server.
1. Rework on the process as you state, it will introduce extra step(s), and break the currently CN user experience.

**Comment by wangmiaowj** [comment]
I can't connect to hoyolab's site normally in mainland China. My computer has set up a proxy and can access Google and hoyolab normally, but the application cannot access hoyolab. Is there any way to make the application go through the proxy?

**Comment by wudifeixue** [comment]
Is this still a work in progress? Currently, some features would work as expected with only UID binding like this. 
![image](https://user-images.githubusercontent.com/7316929/180601347-14fbe016-000c-41ec-93b6-d33b8f98d3b2.png)
I can't bind the cookie successfully, and also I failed to get some of the valuable features such as #练度统计 
![image](https://user-images.githubusercontent.com/7316929/180601397-d6b0f4ee-af5e-4dc8-92b2-5daef4c8c46c.png)
Even though on CN server UID I can get it to work to show some of the characters even if I don't bind any cookies at all. (such as shown below)
![image](https://user-images.githubusercontent.com/7316929/180601454-729ce61d-60eb-4c73-b07d-4b51b66652bd.png)

**Comment by wudifeixue** [comment]
这个问题没有得到解决就被关闭了
